In [1]:
import numpy as np
np.__version__

'1.25.2'

## Python List

In [2]:
gpas_as_list = [4.0, 3.2, 3.5]

In [3]:
gpas_as_list.append(4.0)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

In [5]:
gpas_as_list.insert(1,"Belum ada")
gpas_as_list

[4.0, 'Belum ada', 'Belum ada', 3.2, 3.5, 4.0]

In [7]:
gpas_as_list.pop(1)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

## Numpy Array

In [8]:
gpas = np.array(gpas_as_list)

In [9]:
gpas.dtype

dtype('float64')

In [10]:
gpas.size

4

## Study log

In [12]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

## Array Multidimensi

In [14]:
students_gpas = np.array([
    [4.0, 3.3,3.5 , 4.0],
    [3.96,3.92, 4.0,4.0],
    [3.2, 3.8, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [16]:
students_gpas.ndim#untuk melihat jumlah dimensi

2

In [17]:
students_gpas.shape# mempunyai 3 array memiliki 4 elemen

(3, 4)

In [18]:
students_gpas[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [19]:
students_gpas[2][3]

4.0

## Study Log MultiDimensi

In [21]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [22]:
study_minutes[1][0] = 60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [25]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180 , size=100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [27]:
[fake_log[1],fake_log[21]]

[122, 160]

In [28]:
fake_log[[1,21]]

array([122, 160], dtype=uint16)

In [29]:
index = np.array([
    [1,21],
    [1,2]
])
fake_log[index]

array([[122, 160],
       [122, 128]], dtype=uint16)

In [30]:
study_minutes = np.append(study_minutes,[fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [31]:
practice = np.arange(42)
practice.shape = (7,6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [32]:
practice[2, 1]

13

In [33]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
practice[2:5, 3]

array([15, 21, 27])

In [35]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

## Copy vs View

In [36]:
practice_list = [1,2,3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0] = 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [37]:
not_copied = practice[:]
not_copied[0,0] = 12345
practice, not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [38]:
print(not_copied.base)

[[12345     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]
 [   24    25    26    27    28    29]
 [   30    31    32    33    34    35]
 [   36    37    38    39    40    41]]


In [39]:
not_copied.base is practice

True

## Filter Array dengan Kondisi
### Mencari durasi belajar di bawah 1 jam

In [41]:
fake_log < 60
fake_log[fake_log < 60]

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [43]:
results = []
for value in fake_log:
    if value < 60:
        results.append(value)

np.array(results)

array([44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52, 31,
       57, 37, 58], dtype=uint16)

In [44]:
study_minutes = np.zeros(100, np.uint16)
study_minutes = np.append(study_minutes,[fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0, 132, 122, 128,  44,
       136, 129, 101,  95,  50, 132, 151,  64, 104, 175, 117, 146, 139,
       129, 133, 176,  98, 160, 179,  99,  82, 142,  31, 106, 117,  56,
        98,  67, 121, 159,  81, 170,  31,  50,  49,  87, 179,  51, 116,
       177, 118,  78, 171, 117,  88, 123, 102,  44,  79,  31, 108,  80,
        59, 137,  84,  93, 155, 160,  67,  80, 166, 164,  70,  50, 102,
       113,  47, 131, 161, 118,  82,  89,  81,  43,  81,  38, 11

In [50]:
study_minutes[study_minutes < 60]
study_minutes[(study_minutes < 60) & (study_minutes > 60)]


array([], dtype=uint16)