In [1]:
import numpy as np

In [7]:

b = [[1,2,3],[4,5,6],[7,8,9]]
display(a[0])
b[0]a = np.array([[1,2,3],[4,5,6],[7,8,9]])

array([1, 2, 3])

[1, 2, 3]

In [10]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
#np.zeros(6)#membuat beberapa angka 0 sebanyak angka yang dimasukkan
#np.ones(6)#membuat beberapa angka 1 sebanyak angka yang di inginkan
np.empty(4, order='F')#membuat float secara acak sebanyak yang di inginkan

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.24057726e-311])

In [22]:
cth = np.arange(5,10,2)

In [24]:
# appending 2 or more array
np.append(cth, [1,2,3])

array([5, 7, 9, 1, 2, 3])

In [25]:
# deleting element of array by index
np.delete(cth, 1)

array([5, 9])

In [26]:
cth = np.append(cth,[1,2,10])
np.sort(cth)

array([ 1,  2,  5,  7,  9, 10])

In [28]:
array_example = np.array(
    [
        [
            [0,1,2,3],
            [4,5,6,7]
        ],
        [
            [0,1,2,3],
            [4,5,6,7]
        ],
        [
            [0,1,2,3],
            [4,5,6,7]
        ]
    ]
)
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [29]:
print (array_example.ndim)

print(array_example.size)

print(array_example.shape)

3
24
(3, 2, 4)


In [33]:
array_example = np.array(
        [
            [0,1,2,3],
            [4,5,6,7]
        ]
)
array_example.shape
array_example.ndim
array_example.size

8

In [39]:
a = np.arange(16)
b = a.reshape(2,2,2,2)
b

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [41]:
a.ndim
b.ndim

4

In [44]:
display(a)
a2 = a[np.newaxis]
display(a2)
a3 = a2[np.newaxis]
display(a3)

row_vector = a[:,np.newaxis]
row_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [53]:
a = np.arange(5)
display(a)
display(a.shape)
b = np.expand_dims(a, axis=0)
display(b)
display(b.shape)

array([0, 1, 2, 3, 4])

(5,)

array([[0, 1, 2, 3, 4]])

(1, 5)

In [59]:
print(a[1])
print(a[:3])
print(a[::-1])

1
[0 1 2]
[4 3 2 1 0]


In [60]:
array_example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
array_example[array_example >= 2]

array([2, 3, 4, 5, 6, 7])

In [62]:
five_up = (array_example >= 5)
array_example[five_up]

array([5, 6, 7])

In [65]:
array_example[(array_example%2==0) & (array_example > 3)]
array_example[(array_example%2==0) | (array_example > 3)]

array([0, 2, 4, 5, 6, 7])

In [66]:
a = np.arange(1,11)
b = a[3:8]
b

array([4, 5, 6, 7, 8])

In [67]:
array_example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
a1 = np.array(
    [
        [0,1,],
        [4,5,]
    ]
)
a2 = np.array(
    [
        [2,3,],
        [6,7,]
    ]
)

In [72]:
np.vstack((a1 , a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [73]:
np.hstack((a1 , a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [75]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
b = a.view()
np.vstack((b,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)
a + b

[0 1 2]
[4 5 6]


array([4, 6, 8])

In [82]:
a2.sum()

18

In [83]:
c.sum(axis= 0)

array([15, 18, 21, 24])

In [84]:
print(a)
print(a * 1.6)

[0 1 2]
[0.  1.6 3.2]


In [85]:
print(c.min())
print(c.max())
print(c.sum())
print(c.std())

1
12
78
3.452052529534663


In [89]:
z = np.zeros((6,2))
o = np.ones((6,2))
r = np.random.random((6,2))
print(z)
print(o)
print(r)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.22423572 0.05125386]
 [0.5925501  0.52568625]
 [0.25053739 0.69425958]
 [0.35213151 0.88705611]
 [0.58592668 0.9121214 ]
 [0.00666183 0.29905562]]


In [90]:
r + o

array([[1.22423572, 1.05125386],
       [1.5925501 , 1.52568625],
       [1.25053739, 1.69425958],
       [1.35213151, 1.88705611],
       [1.58592668, 1.9121214 ],
       [1.00666183, 1.29905562]])

In [96]:
a1 = np.array([[0,1,2],[4,5,10],[7,8,9]])
print(a1)
a2 = np.array([[0,1,2],[4,5,6],[8,9,10]])
print(a2)

[[ 0  1  2]
 [ 4  5 10]
 [ 7  8  9]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [97]:
np.dot(a1,a2)

array([[ 20,  23,  26],
       [100, 119, 138],
       [104, 128, 152]])

In [98]:
a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0][1])


[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2


In [99]:
display(a1)
print(a1.shape)
print(a1.T)
print(a1.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [101]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2]])

In [103]:
a1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
arrflat1 = arrflat.flatten()
print(arrflat1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
